Param(
    [Parameter(Mandatory=$True)]
    [string]$botWebchatSecret
)

$ErrorActionPreference = "Stop"

function PostMessage($convId, $userName, $userId, $text) {
    $msg = @{
        "type"="message"
        "text"=$text
        "from" = @{
            "id"=$userId
            "name"=$userName
         }
    } | ConvertTo-Json
    Write-Host "Sending: $text"
    $res=Invoke-WebRequest -Uri "https://directline.botframework.com/v3/directline/conversations/$convId/activities" -Method POST -Body $msg -Headers @{"Authorization" = "Bearer $botWebchatSecret"; "Content-Type" = "application/json"}
}

function performConversation ($question, $answerToAppointmentRequest, $answerToMailRequest) {
    Try {
        $conversationStart=Invoke-WebRequest -Uri "https://directline.botframework.com/v3/directline/conversations" -Method POST -Headers @{"Authorization" = "Bearer $botWebchatSecret"} | ConvertFrom-Json

        $userName="ScriptedUser";
        $convId=$conversationStart.conversationId;
        $myId=(New-Guid);

        PostMessage $convId $userName $myId $question

        Do {
            Write-Host "Getting messages..."
            $messages=Invoke-WebRequest -Uri "https://directline.botframework.com/v3/directline/conversations/$convId/activities" -Headers @{"Authorization" = "Bearer $botWebchatSecret"} | ConvertFrom-Json
            $question=$messages.activities | Where-Object {$_.from.id -ne $myId -and $_.text.EndsWith('?')} | Select-Object -Last 1
        } Until ($question)
            Write-Host "Received: " $question.text
        if ($question.text.Contains("appointment")) {
            PostMessage $convId $userName $myId $answerToAppointmentRequest
            }
            else {
            PostMessage $convId $userName $myId $answerToMailRequest
            }
    }
    Catch {
        Write-Host $_.Exception -ForegroundColor Red
    }
}

performConversation 'Do you still manufacture the Polecat?' 'no' 'yes'
performConversation 'What is the weight of the Sea Otter?' 'yes' 'yes'
performConversation 'The Sable is crap' 'yes' 'no'
performConversation 'What does the Wolverine have as color?' 'no' 'no'
performConversation 'Why is the Polecat so expensive?' 'yes' 'no'
performConversation 'Do you still manufacture the Sea Otter?' 'yes' 'no'
performConversation 'What is the color of the Sable?' 'no' 'yes'
performConversation 'The Wolverine is crap' 'no' 'yes'
performConversation 'What does the Polecat have as mpg?' 'yes' 'no'
performConversation 'Why is the Sea Otter so expensive?' 'yes' 'yes'
performConversation 'Do you still manufacture the Sable?' 'yes' 'no'
performConversation 'What is the mpg of the Wolverine?' 'yes' 'no'
performConversation 'The Polecat is crap' 'yes' 'no'
performConversation 'What does the Sea Otter have as weight?' 'yes' 'yes'
performConversation 'Why is the Sable so expensive?' 'no' 'no'
performConversation 'Do you still manufacture the Wolverine?' 'yes' 'no'
performConversation 'What is the weight of the Polecat?' 'no' 'no'
performConversation 'The Sea Otter is crap' 'yes' 'no'
performConversation 'What does the Sable have as color?' 'no' 'yes'
performConversation 'Why is the Wolverine so expensive?' 'no' 'yes'
performConversation 'Do you still manufacture the Polecat?' 'yes' 'no'
performConversation 'What is the color of the Sea Otter?' 'no' 'yes'
performConversation 'The Sable is crap' 'no' 'no'
performConversation 'What does the Wolverine have as mpg?' 'yes' 'yes'
performConversation 'Why is the Polecat so expensive?' 'no' 'yes'
performConversation 'Do you still manufacture the Sea Otter?' 'yes' 'yes'
performConversation 'What is the mpg of the Sable?' 'no' 'yes'
performConversation 'The Wolverine is crap' 'yes' 'yes'
performConversation 'What does the Polecat have as weight?' 'yes' 'no'
performConversation 'Why is the Sea Otter so expensive?' 'no' 'yes'
performConversation 'Do you still manufacture the Sable?' 'yes' 'yes'
performConversation 'What is the weight of the Wolverine?' 'no' 'no'
performConversation 'The Polecat is crap' 'yes' 'no'
performConversation 'What does the Sea Otter have as color?' 'yes' 'yes'
performConversation 'Why is the Sable so expensive?' 'no' 'yes'
performConversation 'Do you still manufacture the Wolverine?' 'no' 'no'
performConversation 'What is the color of the Polecat?' 'yes' 'yes'
performConversation 'The Sea Otter is crap' 'yes' 'no'
performConversation 'What does the Sable have as mpg?' 'yes' 'no'
performConversation 'Why is the Wolverine so expensive?' 'yes' 'yes'
performConversation 'Do you still manufacture the Polecat?' 'no' 'yes'
performConversation 'What is the mpg of the Sea Otter?' 'yes' 'no'
performConversation 'The Sable is crap' 'yes' 'no'
performConversation 'What does the Wolverine have as weight?' 'no' 'no'
performConversation 'Why is the Polecat so expensive?' 'no' 'no'
performConversation 'Do you still manufacture the Sea Otter?' 'no' 'no'
performConversation 'What is the weight of the Sable?' 'yes' 'yes'
performConversation 'The Wolverine is crap' 'yes' 'no'
performConversation 'What does the Polecat have as color?' 'yes' 'no'
performConversation 'Why is the Sea Otter so expensive?' 'yes' 'no'
performConversation 'Do you still manufacture the Sable?' 'no' 'no'
performConversation 'What is the color of the Wolverine?' 'yes' 'no'
performConversation 'The Polecat is crap' 'yes' 'yes'
performConversation 'What does the Sea Otter have as mpg?' 'yes' 'no'
performConversation 'Why is the Sable so expensive?' 'no' 'yes'
performConversation 'Do you still manufacture the Wolverine?' 'no' 'no'
performConversation 'What is the mpg of the Polecat?' 'no' 'no'
performConversation 'The Sea Otter is crap' 'yes' 'no'
performConversation 'What does the Sable have as weight?' 'yes' 'no'
performConversation 'Why is the Wolverine so expensive?' 'yes' 'no'
performConversation 'Do you still manufacture the Polecat?' 'yes' 'yes'
performConversation 'What is the weight of the Sea Otter?' 'yes' 'no'
performConversation 'The Sable is crap' 'yes' 'no'
performConversation 'What does the Wolverine have as color?' 'no' 'no'
performConversation 'Why is the Polecat so expensive?' 'no' 'no'
performConversation 'Do you still manufacture the Sea Otter?' 'yes' 'no'
performConversation 'What is the color of the Sable?' 'no' 'yes'
performConversation 'The Wolverine is crap' 'yes' 'no'
performConversation 'What does the Polecat have as mpg?' 'yes' 'no'
performConversation 'Why is the Sea Otter so expensive?' 'yes' 'no'
performConversation 'Do you still manufacture the Sable?' 'yes' 'yes'
performConversation 'What is the mpg of the Wolverine?' 'no' 'yes'
performConversation 'The Polecat is crap' 'yes' 'no'
performConversation 'What does the Sea Otter have as weight?' 'yes' 'no'
performConversation 'Why is the Sable so expensive?' 'no' 'no'
performConversation 'Do you still manufacture the Wolverine?' 'no' 'yes'
performConversation 'What is the weight of the Polecat?' 'yes' 'no'
performConversation 'The Sea Otter is crap' 'yes' 'yes'
performConversation 'What does the Sable have as color?' 'no' 'yes'
performConversation 'Why is the Wolverine so expensive?' 'no' 'no'
performConversation 'Do you still manufacture the Polecat?' 'yes' 'no'
performConversation 'What is the color of the Sea Otter?' 'yes' 'no'
performConversation 'The Sable is crap' 'no' 'yes'
performConversation 'What does the Wolverine have as mpg?' 'yes' 'no'
performConversation 'Why is the Polecat so expensive?' 'yes' 'yes'
performConversation 'Do you still manufacture the Sea Otter?' 'yes' 'yes'
performConversation 'What is the mpg of the Sable?' 'no' 'yes'
performConversation 'The Wolverine is crap' 'yes' 'no'
performConversation 'What does the Polecat have as weight?' 'yes' 'yes'
performConversation 'Why is the Sea Otter so expensive?' 'yes' 'no'
performConversation 'Do you still manufacture the Sable?' 'no' 'no'
performConversation 'What is the weight of the Wolverine?' 'no' 'yes'
performConversation 'The Polecat is crap' 'yes' 'no'
performConversation 'What does the Sea Otter have as color?' 'yes' 'no'
performConversation 'Why is the Sable so expensive?' 'yes' 'yes'
performConversation 'Do you still manufacture the Wolverine?' 'no' 'yes'
performConversation 'What is the color of the Polecat?' 'yes' 'no'
performConversation 'The Sea Otter is crap' 'yes' 'yes'
performConversation 'What does the Sable have as mpg?' 'yes' 'no'
performConversation 'Why is the Wolverine so expensive?' 'yes' 'no'
performConversation 'Do you still manufacture the Polecat?' 'yes' 'no'
performConversation 'What is the mpg of the Sea Otter?' 'yes' 'no'
performConversation 'The Sable is crap' 'no' 'yes'
performConversation 'What does the Wolverine have as weight?' 'no' 'no'
performConversation 'Why is the Polecat so expensive?' 'yes' 'yes'
performConversation 'Do you still manufacture the Sea Otter?' 'yes' 'yes'
performConversation 'What is the weight of the Sable?' 'no' 'yes'
performConversation 'The Wolverine is crap' 'yes' 'no'
performConversation 'What does the Polecat have as color?' 'yes' 'no'
performConversation 'Why is the Sea Otter so expensive?' 'yes' 'no'
performConversation 'Do you still manufacture the Sable?' 'no' 'yes'
performConversation 'What is the color of the Wolverine?' 'no' 'yes'
performConversation 'The Polecat is crap' 'yes' 'no'
performConversation 'What does the Sea Otter have as mpg?' 'yes' 'no'
performConversation 'Why is the Sable so expensive?' 'yes' 'yes'
performConversation 'Do you still manufacture the Wolverine?' 'yes' 'yes'
performConversation 'What is the mpg of the Polecat?' 'yes' 'no'
performConversation 'The Sea Otter is crap' 'yes' 'no'
performConversation 'What does the Sable have as weight?' 'yes' 'no'
performConversation 'Why is the Wolverine so expensive?' 'no' 'yes'
performConversation 'Do you still manufacture the Polecat?' 'no' 'yes'
performConversation 'What is the weight of the Sea Otter?' 'no' 'no'
performConversation 'The Sable is crap' 'no' 'no'
performConversation 'What does the Wolverine have as color?' 'yes' 'no'
performConversation 'Why is the Polecat so expensive?' 'yes' 'yes'
performConversation 'Do you still manufacture the Sea Otter?' 'yes' 'no'
performConversation 'What is the color of the Sable?' 'no' 'yes'
performConversation 'The Wolverine is crap' 'yes' 'no'
performConversation 'What does the Polecat have as mpg?' 'yes' 'no'
performConversation 'Why is the Sea Otter so expensive?' 'no' 'no'
performConversation 'Do you still manufacture the Sable?' 'yes' 'no'
performConversation 'What is the mpg of the Wolverine?' 'yes' 'yes'
performConversation 'The Polecat is crap' 'yes' 'no'
performConversation 'What does the Sea Otter have as weight?' 'yes' 'no'
performConversation 'Why is the Sable so expensive?' 'no' 'yes'
performConversation 'Do you still manufacture the Wolverine?' 'no' 'no'
performConversation 'What is the weight of the Polecat?' 'yes' 'yes'
performConversation 'The Sea Otter is crap' 'yes' 'no'
performConversation 'What does the Sable have as color?' 'yes' 'no'
performConversation 'Why is the Wolverine so expensive?' 'yes' 'yes'
performConversation 'Do you still manufacture the Polecat?' 'no' 'no'
performConversation 'What is the color of the Sea Otter?' 'no' 'yes'
performConversation 'The Sable is crap' 'yes' 'no'
performConversation 'What does the Wolverine have as mpg?' 'yes' 'no'
performConversation 'Why is the Polecat so expensive?' 'no' 'no'
performConversation 'Do you still manufacture the Sea Otter?' 'no' 'no'
performConversation 'What is the mpg of the Sable?' 'yes' 'yes'
performConversation 'The Wolverine is crap' 'yes' 'no'
performConversation 'What does the Polecat have as weight?' 'no' 'yes'
performConversation 'Why is the Sea Otter so expensive?' 'yes' 'yes'
performConversation 'Do you still manufacture the Sable?' 'yes' 'yes'
performConversation 'What is the weight of the Wolverine?' 'yes' 'yes'
performConversation 'The Polecat is crap' 'yes' 'no'
performConversation 'What does the Sea Otter have as color?' 'yes' 'no'
performConversation 'Why is the Sable so expensive?' 'yes' 'yes'
performConversation 'Do you still manufacture the Wolverine?' 'no' 'yes'
performConversation 'What is the color of the Polecat?' 'yes' 'yes'
performConversation 'The Sea Otter is crap' 'yes' 'yes'
performConversation 'What does the Sable have as mpg?' 'no' 'no'
performConversation 'Why is the Wolverine so expensive?' 'no' 'no'
performConversation 'Do you still manufacture the Polecat?' 'yes' 'no'
performConversation 'What is the mpg of the Sea Otter?' 'no' 'yes'
performConversation 'The Sable is crap' 'yes' 'yes'
performConversation 'What does the Wolverine have as weight?' 'no' 'yes'
performConversation 'Why is the Polecat so expensive?' 'yes' 'no'
performConversation 'Do you still manufacture the Sea Otter?' 'no' 'no'
performConversation 'What is the weight of the Sable?' 'yes' 'yes'
performConversation 'The Wolverine is crap' 'no' 'yes'
performConversation 'What does the Polecat have as color?' 'no' 'no'
performConversation 'Why is the Sea Otter so expensive?' 'yes' 'no'
performConversation 'Do you still manufacture the Sable?' 'no' 'yes'
performConversation 'What is the color of the Wolverine?' 'no' 'no'
performConversation 'The Polecat is crap' 'yes' 'no'
performConversation 'What does the Sea Otter have as mpg?' 'no' 'no'
performConversation 'Why is the Sable so expensive?' 'yes' 'yes'
performConversation 'Do you still manufacture the Wolverine?' 'no' 'no'
performConversation 'What is the mpg of the Polecat?' 'no' 'yes'
performConversation 'The Sea Otter is crap' 'no' 'yes'
performConversation 'What does the Sable have as weight?' 'no' 'yes'
performConversation 'Why is the Wolverine so expensive?' 'yes' 'no'
performConversation 'Do you still manufacture the Polecat?' 'yes' 'yes'
performConversation 'What is the weight of the Sea Otter?' 'yes' 'no'
performConversation 'The Sable is crap' 'yes' 'yes'
performConversation 'What does the Wolverine have as color?' 'no' 'no'
performConversation 'Why is the Polecat so expensive?' 'yes' 'yes'
performConversation 'Do you still manufacture the Sea Otter?' 'yes' 'no'
performConversation 'What is the color of the Sable?' 'no' 'yes'
performConversation 'The Wolverine is crap' 'yes' 'no'
performConversation 'What does the Polecat have as mpg?' 'no' 'yes'
performConversation 'Why is the Sea Otter so expensive?' 'yes' 'yes'
performConversation 'Do you still manufacture the Sable?' 'no' 'no'
performConversation 'What is the mpg of the Wolverine?' 'no' 'yes'
performConversation 'The Polecat is crap' 'no' 'yes'
performConversation 'What does the Sea Otter have as weight?' 'yes' 'no'
performConversation 'Why is the Sable so expensive?' 'no' 'yes'
performConversation 'Do you still manufacture the Wolverine?' 'no' 'no'
performConversation 'What is the weight of the Polecat?' 'no' 'no'
performConversation 'The Sea Otter is crap' 'yes' 'yes'
performConversation 'What does the Sable have as color?' 'yes' 'no'
performConversation 'Why is the Wolverine so expensive?' 'yes' 'no'
performConversation 'Do you still manufacture the Polecat?' 'yes' 'no'
performConversation 'What is the color of the Sea Otter?' 'yes' 'no'
performConversation 'The Sable is crap' 'yes' 'yes'
performConversation 'What does the Wolverine have as mpg?' 'yes' 'no'
performConversation 'Why is the Polecat so expensive?' 'yes' 'no'
performConversation 'Do you still manufacture the Sea Otter?' 'yes' 'no'
performConversation 'What is the mpg of the Sable?' 'no' 'yes'
performConversation 'The Wolverine is crap' 'no' 'yes'
performConversation 'What does the Polecat have as weight?' 'no' 'no'
performConversation 'Why is the Sea Otter so expensive?' 'yes' 'no'
performConversation 'Do you still manufacture the Sable?' 'no' 'yes'
performConversation 'What is the weight of the Wolverine?' 'no' 'yes'
performConversation 'The Polecat is crap' 'yes' 'yes'
performConversation 'What does the Sea Otter have as color?' 'yes' 'yes'
performConversation 'Why is the Sable so expensive?' 'yes' 'no'
performConversation 'Do you still manufacture the Wolverine?' 'yes' 'no'
performConversation 'What is the color of the Polecat?' 'yes' 'no'
performConversation 'The Sea Otter is crap' 'no' 'no'
performConversation 'What does the Sable have as mpg?' 'no' 'yes'
performConversation 'Why is the Wolverine so expensive?' 'no' 'no'
performConversation 'Do you still manufacture the Polecat?' 'yes' 'yes'
performConversation 'What is the mpg of the Sea Otter?' 'no' 'yes'
performConversation 'The Sable is crap' 'no' 'no'
performConversation 'What does the Wolverine have as weight?' 'yes' 'no'
performConversation 'Why is the Polecat so expensive?' 'no' 'no'
performConversation 'Do you still manufacture the Sea Otter?' 'yes' 'no'
performConversation 'What is the weight of the Sable?' 'no' 'yes'
performConversation 'The Wolverine is crap' 'yes' 'no'
performConversation 'What does the Polecat have as color?' 'yes' 'yes'
performConversation 'Why is the Sea Otter so expensive?' 'yes' 'no'
performConversation 'Do you still manufacture the Sable?' 'no' 'yes'
performConversation 'What is the color of the Wolverine?' 'yes' 'yes'
performConversation 'The Polecat is crap' 'no' 'yes'
performConversation 'What does the Sea Otter have as mpg?' 'no' 'no'
performConversation 'Why is the Sable so expensive?' 'yes' 'no'
performConversation 'Do you still manufacture the Wolverine?' 'yes' 'yes'
performConversation 'What is the mpg of the Polecat?' 'no' 'no'
performConversation 'The Sea Otter is crap' 'yes' 'no'
performConversation 'What does the Sable have as weight?' 'yes' 'no'
performConversation 'Why is the Wolverine so expensive?' 'yes' 'no'
performConversation 'Do you still manufacture the Polecat?' 'yes' 'no'
performConversation 'What is the weight of the Sea Otter?' 'no' 'no'
performConversation 'The Sable is crap' 'yes' 'no'
performConversation 'What does the Wolverine have as color?' 'yes' 'no'
performConversation 'Why is the Polecat so expensive?' 'yes' 'yes'
performConversation 'Do you still manufacture the Sea Otter?' 'yes' 'no'
performConversation 'What is the color of the Sable?' 'no' 'yes'
performConversation 'The Wolverine is crap' 'yes' 'no'
performConversation 'What does the Polecat have as mpg?' 'yes' 'no'
performConversation 'Why is the Sea Otter so expensive?' 'no' 'no'
performConversation 'Do you still manufacture the Sable?' 'no' 'no'
performConversation 'What is the mpg of the Wolverine?' 'yes' 'yes'
performConversation 'The Polecat is crap' 'no' 'yes'
performConversation 'What does the Sea Otter have as weight?' 'yes' 'yes'
performConversation 'Why is the Sable so expensive?' 'yes' 'yes'
performConversation 'Do you still manufacture the Wolverine?' 'no' 'no'
performConversation 'What is the weight of the Polecat?' 'yes' 'no'
performConversation 'The Sea Otter is crap' 'yes' 'no'
performConversation 'What does the Sable have as color?' 'no' 'no'
performConversation 'Why is the Wolverine so expensive?' 'no' 'no'
performConversation 'Do you still manufacture the Polecat?' 'no' 'yes'
performConversation 'What is the color of the Sea Otter?' 'yes' 'no'
performConversation 'The Sable is crap' 'yes' 'no'
performConversation 'What does the Wolverine have as mpg?' 'no' 'no'
performConversation 'Why is the Polecat so expensive?' 'no' 'yes'
performConversation 'Do you still manufacture the Sea Otter?' 'no' 'yes'
performConversation 'What is the mpg of the Sable?' 'yes' 'yes'
performConversation 'The Wolverine is crap' 'no' 'no'
performConversation 'What does the Polecat have as weight?' 'yes' 'no'
performConversation 'Why is the Sea Otter so expensive?' 'yes' 'yes'
performConversation 'Do you still manufacture the Sable?' 'no' 'no'
performConversation 'What is the weight of the Wolverine?' 'no' 'yes'
performConversation 'The Polecat is crap' 'yes' 'no'
performConversation 'What does the Sea Otter have as color?' 'yes' 'no'
performConversation 'Why is the Sable so expensive?' 'no' 'yes'
performConversation 'Do you still manufacture the Wolverine?' 'yes' 'yes'
performConversation 'What is the color of the Polecat?' 'yes' 'yes'
performConversation 'The Sea Otter is crap' 'yes' 'no'
performConversation 'What does the Sable have as mpg?' 'no' 'no'
performConversation 'Why is the Wolverine so expensive?' 'yes' 'yes'
performConversation 'Do you still manufacture the Polecat?' 'yes' 'no'
performConversation 'What is the mpg of the Sea Otter?' 'yes' 'yes'
performConversation 'The Sable is crap' 'yes' 'yes'
performConversation 'What does the Wolverine have as weight?' 'no' 'yes'
performConversation 'Why is the Polecat so expensive?' 'yes' 'no'
performConversation 'Do you still manufacture the Sea Otter?' 'yes' 'no'
performConversation 'What is the weight of the Sable?' 'yes' 'no'
performConversation 'The Wolverine is crap' 'no' 'no'
performConversation 'What does the Polecat have as color?' 'yes' 'no'
performConversation 'Why is the Sea Otter so expensive?' 'no' 'no'
performConversation 'Do you still manufacture the Sable?' 'no' 'no'
performConversation 'What is the color of the Wolverine?' 'no' 'no'
performConversation 'The Polecat is crap' 'yes' 'no'
performConversation 'What does the Sea Otter have as mpg?' 'yes' 'no'
performConversation 'Why is the Sable so expensive?' 'yes' 'yes'
performConversation 'Do you still manufacture the Wolverine?' 'no' 'yes'
performConversation 'What is the mpg of the Polecat?' 'yes' 'yes'
performConversation 'The Sea Otter is crap' 'yes' 'no'
performConversation 'What does the Sable have as weight?' 'no' 'no'


